'use client';
import { useMemo, useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Bell, Compass, Earth, Heart, Home, MapPin, MessageCircle, Plane, Plus, Search, Send, Sparkles, UserRound, ChevronRight, Clock3, Route, Bookmark, Settings2, ShieldCheck } from 'lucide-react';
import { destinations, posts, stats } from '@/lib/demo';

type Tab = 'home'|'explore'|'globe'|'trips'|'profile';
const nav = [
  ['home','Home',Home],['explore','Explore',Compass],['globe','Globe',Earth],['trips','Trips',Plane],['profile','Profile',UserRound]
] as const;

function Glass({children,className=''}:{children:React.ReactNode,className?:string}){return <div className={`glass ${className}`}>{children}</div>}
function Avatar({text}:{text:string}){return <div className="avatar">{text}</div>}

function NextFlight(){return <Glass className="flight-card">
  <div className="eyebrow"><span>Next flight</span><span className="status"><i/>On time</span></div>
  <div className="route-row"><div><b>SFO</b><small>San Francisco</small></div><div className="route-line"><Plane size={17}/></div><div className="align-r"><b>NRT</b><small>Tokyo</small></div></div>
  <div className="flight-meta"><span>UA837</span><span>Sep 10 · 11:20 AM</span><span>11h 10m</span></div>
  <div className="countdown"><div><Clock3 size={16}/><span>Departure in</span></div><strong>28 days</strong></div>
  <div className="same-flight"><div className="stack"><Avatar text="AC"/><Avatar text="JL"/><Avatar text="+3"/></div><div><b>You’re not flying alone</b><small>5 travelers are also on UA837</small></div><ChevronRight size={18}/></div>
</Glass>}

function Feed(){const [liked,setLiked]=useState<number[]>([1]);return <div className="feed">
  {posts.map((p,i)=><motion.article initial={{opacity:0,y:14}} animate={{opacity:1,y:0}} transition={{delay:.05*i}} key={p.id} className="post glass">
    <div className="post-head"><Avatar text={p.initials}/><div><b>{p.name}</b><small>{p.handle} · {p.place}</small></div><button>•••</button></div>
    <div className="post-flight"><div><Plane size={15}/><b>{p.route}</b></div><span>{p.flight}</span></div>
    <div className="photo" style={{background:p.image}}><div className="photo-overlay"><MapPin size={14}/> {p.place}</div><div className="photo-art"><span>✦</span><b>{p.place.split(',')[0]}</b><small>travel memory</small></div></div>
    <p>{p.caption}</p>
    <div className="actions"><div><button onClick={()=>setLiked(x=>x.includes(p.id)?x.filter(v=>v!==p.id):[...x,p.id])} className={liked.includes(p.id)?'liked':''}><Heart size={20} fill={liked.includes(p.id)?'currentColor':'none'}/>{p.likes+(liked.includes(p.id)&&p.id!==1?1:0)}</button><button><MessageCircle size={20}/>{p.comments}</button><button><Send size={19}/></button></div><button><Bookmark size={19}/></button></div>
  </motion.article>)}
</div>}

function HomeView(){return <><div className="mobile-title"><div><small>Good evening,</small><h1>Chris <span>✈</span></h1></div><button className="circle"><Bell size={20}/><i/></button></div><NextFlight/><div className="section-title"><h2>Friends traveling</h2><button>See all</button></div><div className="stories">{['Alex|Seoul|🇰🇷','Maya|Tokyo|🇯🇵','Daniel|Paris|🇫🇷','Sofia|Rome|🇮🇹'].map(x=>{const [n,c,e]=x.split('|');return <div className="story" key={n}><div className="story-ring"><Avatar text={n.slice(0,2).toUpperCase()}/><span>{e}</span></div><b>{n}</b><small>{c}</small></div>})}</div><div className="section-title"><h2>Recent journeys</h2><button>Following</button></div><Feed/></>}

function ExploreView(){return <div><div className="page-title"><div><span className="kicker">DISCOVER</span><h1>Where to next?</h1><p>Travel inspiration, interesting people, and routes worth taking.</p></div></div><div className="search"><Search size={18}/><input placeholder="Search cities, airports, flights, travelers…"/></div><div className="section-title"><h2>Trending destinations</h2><button>View map</button></div><div className="destination-grid">{destinations.map((d,i)=><Glass className="destination" key={d.city}><div className={`dest-art a${i}`}><span>{d.emoji}</span></div><h3>{d.city}</h3><p>{d.country}</p><small>{d.travelers} travelers this week</small></Glass>)}</div><div className="section-title"><h2>Popular routes</h2><button>See all</button></div><Glass className="route-list">{[['SFO','NRT','5,142'],['JFK','CDG','4,806'],['LAX','HND','4,313'],['LHR','JFK','3,955']].map((r,i)=><div className="route-item" key={r[0]}><span className="rank">0{i+1}</span><b>{r[0]} <Plane size={14}/> {r[1]}</b><small>{r[2]} travelers</small><ChevronRight size={17}/></div>)}</Glass></div>}

function GlobeView(){const [focus,setFocus]=useState('SFO'); const city=useMemo(()=>focus==='SFO'?'San Francisco':'Tokyo',[focus]); return <div className="globe-page"><div className="globe-copy"><span className="kicker">YOUR WORLD</span><h1>84,530 miles.<br/>One story.</h1><p>Rotate through your travel history and relive every route.</p><div className="globe-stats"><span><b>18</b>countries</span><span><b>42</b>airports</span><span><b>67</b>flights</span></div></div><div className="globe-wrap"><div className="orbit o1"/><div className="orbit o2"/><motion.div className="earth" animate={{rotate:[0,2,-1,0]}} transition={{duration:9,repeat:Infinity}}><div className="continent c1"/><div className="continent c2"/><div className="continent c3"/><motion.div className="arc" animate={{opacity:[.55,1,.55]}} transition={{duration:2,repeat:Infinity}}/><button onClick={()=>setFocus('SFO')} className="pin p1"><i/>SFO</button><button onClick={()=>setFocus('NRT')} className="pin p2"><i/>NRT</button></motion.div><Glass className="globe-pop"><span>{focus}</span><b>{city}</b><small>{focus==='SFO'?'Home airport · 24 flights':'Visited 4 times · 18,432 mi'}</small></Glass></div></div>}

function TripsView(){return <div><div className="page-title row-title"><div><span className="kicker">TRAVEL LOG</span><h1>Your trips</h1><p>Every route, memory and mile in one place.</p></div><button className="primary"><Plus size={18}/> Add flight</button></div><div className="trip-layout"><Glass className="upcoming"><div className="eyebrow">UPCOMING TRIP <span>28 days</span></div><h2>Japan 2026 🇯🇵</h2><p>Sep 10 – Sep 24 · 4 flights · 3 cities</p><div className="timeline">{[['Sep 10','SFO','NRT','UA837'],['Sep 14','HND','ITM','NH25'],['Sep 18','KIX','ICN','KE722'],['Sep 24','ICN','SFO','UA892']].map((f,i)=><div className="timeline-row" key={f[3]}><span>{f[0]}</span><i className={i===0?'active':''}/><div><b>{f[1]} → {f[2]}</b><small>{f[3]}</small></div></div>)}</div></Glass><div><h3 className="mini-heading">Past trips</h3>{[['Honolulu Escape','May 2026','2 flights · 4,794 mi','🏝️'],['New York Weekend','Mar 2026','2 flights · 5,136 mi','🗽'],['Europe Winter','Dec 2025','6 flights · 14,802 mi','🏔️']].map(t=><Glass className="past-trip" key={t[0]}><span>{t[3]}</span><div><b>{t[0]}</b><small>{t[1]} · {t[2]}</small></div><ChevronRight size={18}/></Glass>)}</div></div></div>}

function ProfileView(){return <div><Glass className="profile-head"><div className="cover"><div className="profile-avatar">CN</div></div><div className="profile-body"><div className="profile-actions"><button><Settings2 size={18}/></button><button className="primary">Edit profile</button></div><h1>Chris Nguyen <span>✓</span></h1><p>@chrisflies · San Francisco Bay Area</p><p className="bio">Data, aviation, and finding the next city worth getting lost in. ✈️</p><div className="follow"><b>842 <small>followers</small></b><b>391 <small>following</small></b></div><div className="badges"><span>🌎 Globe Trotter</span><span>✈️ Frequent Flyer</span><span>🌙 Night Owl</span></div></div></Glass><div className="section-title"><h2>Travel statistics</h2><button>2026</button></div><div className="stat-grid">{stats.map((s,i)=><Glass className="stat" key={s[0]}><span className={`stat-icon s${i}`}>{[<Plane key="p"/>,<Route key="r"/>,<Earth key="e"/>,<MapPin key="m"/>,<Clock3 key="c"/>,<Sparkles key="s"/>][i]}</span><strong>{s[1]}</strong><small>{s[0]}</small></Glass>)}</div><Glass className="privacy"><ShieldCheck size={24}/><div><b>Privacy first</b><small>Upcoming flights are visible only to approved followers. Exact location sharing is off.</small></div><ChevronRight/></Glass></div>}

export default function Page(){const [tab,setTab]=useState<Tab>('home'); return <main><aside className="sidebar"><div className="brand"><div><Plane size={20}/></div><span>skyline</span></div><nav>{nav.map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} className={tab===id?'active':''}><Icon size={21}/><span>{label}</span></button>)}</nav><button className="add"><Plus size={20}/> Add flight</button><div className="mini-profile"><Avatar text="CN"/><div><b>Chris Nguyen</b><small>@chrisflies</small></div><span>•••</span></div></aside><section className="content"><header className="desktop-head"><div><small>Good evening,</small><b>Chris <span>✈</span></b></div><div><button className="search-btn"><Search size={18}/> Search</button><button className="circle"><Bell size={19}/><i/></button></div></header><AnimatePresence mode="wait"><motion.div key={tab} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-6}} transition={{duration:.2}} className={tab==='globe'?'view globe-view':'view'}>{tab==='home'&&<HomeView/>}{tab==='explore'&&<ExploreView/>}{tab==='globe'&&<GlobeView/>}{tab==='trips'&&<TripsView/>}{tab==='profile'&&<ProfileView/>}</motion.div></AnimatePresence></section><aside className="rightbar"><NextFlight/><div className="section-title"><h3>Trending now</h3></div>{destinations.map(d=><div className="trend" key={d.city}><span>{d.emoji}</span><div><b>{d.city}</b><small>{d.travelers} travelers</small></div><ChevronRight size={16}/></div>)}<Glass className="insight"><Sparkles size={18}/><b>Your 2026 is taking off</b><p>You’ve flown 47,291 miles — farther than 88% of travelers in your circle.</p><button>See year in review</button></Glass></aside><div className="mobile-nav">{nav.map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} className={tab===id?'active':''}><Icon size={20}/><small>{label}</small></button>)}<button className="mobile-plus"><Plus size={23}/></button></div></main>}
